# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('what', models.CharField(blank=True, max_length=200, null=True)),
                ('when', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
